### ISSUE TITLE
[Web Components Template] Include Carbon Theme Zoning Classes CDN 

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom-web-components-template#16]
## Summary
- Looks like in this project we're using `carbon--theme()` mixin (eg. https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template/blob/main/src/assets/scss/app.scss#L13) to define the theme of a particular layout component, however, I think it would be helpful to be able to leverage the existing [Carbon theme zoning classes](https://www.ibm.com/standards/carbon/developing/carbon-cdn-style-helpers/#carbon-theme-zoning-classes) CDN helper.
- This allows adopters to easily define the theme using Carbon theme utility classes.

```
<dds-leadspace size="medium" class="dds-theme-zone-g90">
      <dds-leadspace-heading>LeadSpace title</dds-leadspace-heading>
      LeadSpace copy
</dds-leadspace>  
```

## Relevant information

- Add the CDN link to the base page.  
 - Add documentation on how to use it.
- Add documentation on instructions for removal is not using it.

**Comment by RobertaJHahn** [comment]
Include in the Sept 13 Engineering Issues Refinement meeting.
