### ISSUE TITLE
[Web Components Template] Update config to automate language page creation

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom-web-components-template#4]
### The problem
Translation data is currently captured in separate json files. In addition, the language/locale folders are also generated manually within the webpack config. This is overhead configuration that could lead to misconfigurations, as well as additional management for adopters of this template.

### The solution
This should be updated so that the language/local folders are auto-generated based on the existence of the language files.

### Additional information
 - We should also account for cases where languages are not necessary, so that the language folders aren't generated if the translation files are empty, or perhaps a configuration that would disable this feature and only take in the data from a single set of i18n data.
 - This template would be used by adopters to create a new repo to build their own experience.

**Comment by RobertaJHahn** [comment]
Include in the 8/2 engineering refinement meeting agenda.
